"""add city address phone to students

Revision ID: 53a0abefc1f4
Revises: f4c9b37b7fbd
Create Date: 2025-12-26 17:53:28.548931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a0abefc1f4'
down_revision: Union[str, Sequence[str], None] = 'f4c9b37b7fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone')
    op.drop_column('students', 'address')
    op.drop_column('students', 'city')
    # ### end Alembic commands ###
